# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        ./build_linux.sh archive
        echo "TIMESTAMP=`date '+%Y%m%d%H%M'`" >> $GITHUB_ENV
      shell: bash
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binaries-${{ env.TIMESTAMP }}
        path: archive/*.tar.gz
        retention-days: 30
  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        run: ./release.sh
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
